name: Update Jira Ticket Status To Backlog

on:
  issues:
    types:
      - reopened

jobs:
  create_jira_issue:
    uses: XeroAPI/Xero-OpenAPI/.github/workflows/jira_update_issue_reopen.yml@master
    secrets: inherit
