name: Update Jira Ticket Status To Done

on:
  issues:
    types:
      - closed

jobs:
  create_jira_issue:
    uses: XeroAPI/Xero-OpenAPI/.github/workflows/jira_update_issue_closed.yml@master
    secrets: inherit
